server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Panman319.
    url: jdbc:postgres://panman-postgres.crngngslslkl.eu-central-1.rds.amazonaws.com:5432/panman-postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true